In [1]:
import numpy as np

In [2]:
# define training data

X = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]]) # training inputs
y = np.array([[0,1,1,0]]).T # training outputs/labels

In [3]:
print(X)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [4]:
print(y)

[[0]
 [1]
 [1]
 [0]]


In [7]:
num_features = len(X[0])
num_output = len(y[0])

In [8]:
print(num_features, num_output)

3 1


In [62]:
class NeuralNetwork():
    
    def __init__(self, inputs, labels, epochs=10000):
        
        self.X = inputs
        self.y = labels
        self.num_features = len(inputs[0])
        self.num_output = len(labels[0])
        self.epochs = epochs
        self.weights = 2*np.random.random((num_features,num_output))-1
        self.gradients = None
        
    def sigmoid(self, weighted_input):
        return 1/(1+np.exp(-weighted_input))
    
    def sigmoid_derivative(self, output):
        return output*(1-output)
        
    def train(self):
        
        for i in range(self.epochs): # train for number of epochs
            
            y_hat = np.dot(self.X, self.weights)
            
            predicted_y = self.sigmoid(y_hat)
            
            #error = np.sum(np.square(predicted_y - self.y))/self.X.shape[0]
            
            error = y - predicted_y
            
            self.gradients = np.dot(self.X.T, error*self.sigmoid_derivative(predicted_y))
        
            self.weights = self.weights + self.gradients
            
    def predict(self, input):
        
        return self.sigmoid(np.dot(input, self.weights))
        

In [63]:
nn = NeuralNetwork(X, y)

In [64]:
nn.train()

In [65]:
nn.predict([1,0,0])

array([ 0.99993703])

In [66]:
nn.predict([0,0,0])

array([ 0.5])

In [67]:
nn.predict([0,0,1])

array([ 0.0096697])

In [68]:
nn.weights

array([[ 9.6727644 ],
       [-0.20864953],
       [-4.62904143]])

In [69]:
nn.gradients

array([[  1.02473296e-04],
       [  3.18200007e-07],
       [ -5.14820911e-05]])

In [71]:
nn.sigmoid_derivative(y)

array([[0],
       [0],
       [0],
       [0]])